### ISSUE TITLE
may I please have "open_with_unicode" under a more permissive licence?

### ISSUE THREAD

**Issue by zooko** [ambimorph/recluse#1]
Dear Amber:

Thanks for this code! I want to re-use "open_with_unicode" in other (non-linguistics-related) codebases. I'd like to add it into pyutil (https://github.com/zooko/pyutil). May I please have permission to use "open_with_unicode" under a permissive Free and Open Source licence?

**Comment by ambimorph** [comment]
Dear Zooko,

Almost certainly.  Would you be willing to submit a patch to the COPYING file that covers your needs?

**Comment by zooko** [comment]
How about this: you post a comment to this github issue thread saying that I may use the contents of open_with_unicode() (below) under these terms: "Permission is hereby granted to any person obtaining a copy of this work to deal in this work without restriction (including the rights to use, modify, distribute, sublicense, and/or sell copies).". Then I'll copy the code into pyutil. If anyone is ever afraid that they can't use pyutil because they're afraid you might sue them, their fears will be assuaged by the comment on this github ticket. You don't have to change the COPYING file in recluse. Unless you want to!

```
import codecs, bz2, gzip

def open_with_unicode(file_name, mode, compression_type=None):
    assert compression_type in [None, 'gzip', 'bzip2']
    assert mode in ['r', 'w']

    open_fn_dict = {None: open, 'gzip': gzip.GzipFile, 'bzip2': bz2.BZ2File}

    if mode == 'r':
        streamer = codecs.getreader
    elif mode == 'w':
        streamer = codecs.getwriter

    return streamer('utf-8')(open_fn_dict[compression_type](file_name, mode))
```

**Comment by ambimorph** [comment]
Permission is hereby granted to any person obtaining a copy of this work to deal in this work without restriction (including the rights to use, modify, distribute, sublicense, and/or sell copies).

**Comment by zooko** [comment]
Thanks!
